events {}

http {
  upstream filesystem_backend {
    server filesystem-service:8082;
  }

  server {
    listen 8080;

    location / {
      proxy_pass http://filesystem_backend;
      proxy_set_header X-Correlation-Id $http_x_correlation_id;
      proxy_set_header X-Internal-Token $http_x_internal_token;
    }
  }
}

